accept=keyboard,97;joystick,1
cancel=keyboard,98;joystick,0
altleft=keyboard,109;joystick,4
altright=keyboard,110;joystick,5
menu=keyboard,107;joystick,8
settings=keyboard,115;joystick,9
up=keyboard,117;
down=keyboard,100;
left=keyboard,108;
right=keyboard,114;
home=keyboard,113;joystick,12
